# # 1. Upgrade to Premium SKU (Required for Private Link)
resource "azurerm_cdn_frontdoor_profile" "main" {
  name                = var.frontdoor_profile_name
  resource_group_name = var.azurerm_resource_group
  sku_name            = var.frontdoor_sku_name
}

resource "azurerm_cdn_frontdoor_endpoint" "main" {
  name                     = var.frontdoor_endpoint_name
  cdn_frontdoor_profile_id = azurerm_cdn_frontdoor_profile.main.id
}

resource "azurerm_cdn_frontdoor_route" "http_route" {
  name                          = "default-http-route"
  cdn_frontdoor_endpoint_id     = azurerm_cdn_frontdoor_endpoint.main.id
  cdn_frontdoor_origin_group_id = azurerm_cdn_frontdoor_origin_group.aks.id

  # FIX: You must explicitly link the origins created by your for_each loop
  cdn_frontdoor_origin_ids = [for p in azurerm_cdn_frontdoor_origin.aks : p.id]

  supported_protocols    = ["Http"]
  https_redirect_enabled = false
  forwarding_protocol    = "HttpOnly"
  patterns_to_match      = ["/*"]
}


# # --- AKS / Traefik Origin with Private Link ---
resource "azurerm_cdn_frontdoor_origin_group" "aks" {
  name                     = "aks-group"
  cdn_frontdoor_profile_id = azurerm_cdn_frontdoor_profile.main.id
  session_affinity_enabled = false

  load_balancing {
    additional_latency_in_milliseconds = 1000
  }

  health_probe {
    protocol            = "Http"
    interval_in_seconds = 30
    path                = "/ping" # Use a path Traefik is configured to answer
    request_type        = "HEAD"  # Lightweight check
  }
}

resource "azurerm_cdn_frontdoor_origin" "aks" {
  for_each = toset(var.secondary_enabled ? ["primary", "secondary"] : ["primary"])

  name                           = "aks-origin-${each.key}"
  cdn_frontdoor_origin_group_id  = azurerm_cdn_frontdoor_origin_group.aks.id
  enabled                        = var.infra_profile == "dual" ? true : (each.key == var.infra_profile)
  host_name                      = azurerm_public_ip.traefik_lb_ip[each.key].ip_address
  origin_host_header             = azurerm_cdn_frontdoor_endpoint.main.host_name
  certificate_name_check_enabled = false

  # Priority based on infra_profile
  # dual mode: primary=1, secondary=1 (equal priority, load balanced)
  # primary mode: primary=1, secondary=2 (primary preferred, secondary backup)
  # secondary mode: primary=2, secondary=1 (secondary preferred, primary backup)
  priority = 1
  weight   = 500 # Equal weight distribution (50/50) in dual mode

  # Private Link for AKS (via Private Link Service)
  # private_link {
  #   request_message        = "Access from Front Door to Traefik ${each.key}"
  #   location               = each.key == "primary" ? var.location : var.secondary_location
  #   private_link_target_id = "/subscriptions/${var.subscription_id}/resourceGroups/mc_${var.azurerm_resource_group}_${var.aks_name}_${each.key == "primary" ? var.location : var.secondary_location}/providers/Microsoft.Network/privateLinkServices/${each.key}-traefik-frontdoor-pls"
  # }
}

resource "azurerm_public_ip" "traefik_lb_ip" {
  for_each = toset(var.secondary_enabled ? ["primary", "secondary"] : ["primary"])

  name = "traefik-static-ip-${each.key}"

  # DYNAMIC REFERENCE: Uses the actual group name generated by Azure
  resource_group_name = azurerm_kubernetes_cluster.aks[each.key].node_resource_group

  # DYNAMIC LOCATION: Ensures the IP and Cluster are in the same region
  location = azurerm_kubernetes_cluster.aks[each.key].location

  allocation_method = "Static"
  sku               = "Standard"
}

# resource "azurerm_network_security_rule" "only_allow_frontdoor" {
#   name                        = "AllowFrontDoorOnly"
#   priority                    = 100
#   direction                   = "Inbound"
#   access                      = "Allow"
#   protocol                    = "Tcp"
#   source_address_prefix       = "AzureFrontDoor.Backend"
#   source_port_range           = "*"
#   destination_address_prefix  = "*"
#   destination_port_range      = "80"
#   resource_group_name         = var.azurerm_resource_group
#   network_security_group_name = azurerm_kubernetes_cluster.aks["primary"].network_profile[0].network_plugin_profile[0].network_plugin_ns_group_name
# }
